/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package meusus;

/**
 *
 * @author daian
 */
public class meusus extends javax.swing.JFrame {

    /**
     * Creates new form meusus
     */
    public meusus() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        cell26 = new meusus.Cell();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cell1 = new meusus.Cell();
        cell2 = new meusus.Cell();
        cell3 = new meusus.Cell();
        cell4 = new meusus.Cell();
        cell5 = new meusus.Cell();
        cell6 = new meusus.Cell();
        cell7 = new meusus.Cell();
        cell8 = new meusus.Cell();
        cell9 = new meusus.Cell();
        cell10 = new meusus.Cell();
        cell11 = new meusus.Cell();
        cell12 = new meusus.Cell();
        cell13 = new meusus.Cell();
        cell14 = new meusus.Cell();
        cell15 = new meusus.Cell();
        cell16 = new meusus.Cell();
        cell17 = new meusus.Cell();
        cell18 = new meusus.Cell();
        cell19 = new meusus.Cell();
        cell20 = new meusus.Cell();
        cell21 = new meusus.Cell();
        cell22 = new meusus.Cell();
        cell23 = new meusus.Cell();
        cell24 = new meusus.Cell();
        cell25 = new meusus.Cell();
        cell27 = new meusus.Cell();
        cell28 = new meusus.Cell();
        cell29 = new meusus.Cell();
        cell30 = new meusus.Cell();
        cell31 = new meusus.Cell();
        cell32 = new meusus.Cell();
        cell33 = new meusus.Cell();
        cell34 = new meusus.Cell();
        cell35 = new meusus.Cell();
        cell36 = new meusus.Cell();
        cell37 = new meusus.Cell();
        cell38 = new meusus.Cell();
        cell39 = new meusus.Cell();
        cell40 = new meusus.Cell();
        cell41 = new meusus.Cell();
        cell42 = new meusus.Cell();
        cell43 = new meusus.Cell();
        cell44 = new meusus.Cell();
        cell45 = new meusus.Cell();
        cell46 = new meusus.Cell();
        cell47 = new meusus.Cell();
        cell48 = new meusus.Cell();
        cell49 = new meusus.Cell();
        cell50 = new meusus.Cell();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        cell26.setText("16");
        cell26.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jInternalFrame2.setVisible(true);

        javax.swing.GroupLayout jInternalFrame2Layout = new javax.swing.GroupLayout(jInternalFrame2.getContentPane());
        jInternalFrame2.getContentPane().setLayout(jInternalFrame2Layout);
        jInternalFrame2Layout.setHorizontalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame2Layout.setVerticalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Maio");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel3.add(jLabel2, gridBagConstraints);

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 580, 50));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel2.setLayout(new java.awt.GridLayout(7, 7));

        cell1.setText("Segunda-feira");
        cell1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cell1ActionPerformed(evt);
            }
        });
        jPanel2.add(cell1);

        cell2.setText("Terça-feira");
        cell2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cell2ActionPerformed(evt);
            }
        });
        jPanel2.add(cell2);

        cell3.setText("Quarta-feira");
        cell3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cell3ActionPerformed(evt);
            }
        });
        jPanel2.add(cell3);

        cell4.setText("Quinta-feira");
        jPanel2.add(cell4);

        cell5.setText("Sexta-feira");
        jPanel2.add(cell5);

        cell6.setText("Sábado");
        jPanel2.add(cell6);

        cell7.setText("Domingo");
        cell7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cell7ActionPerformed(evt);
            }
        });
        jPanel2.add(cell7);

        cell8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cell8ActionPerformed(evt);
            }
        });
        jPanel2.add(cell8);
        jPanel2.add(cell9);

        cell10.setText("01");
        jPanel2.add(cell10);

        cell11.setText("02");
        jPanel2.add(cell11);

        cell12.setText("03");
        jPanel2.add(cell12);

        cell13.setText("04");
        jPanel2.add(cell13);

        cell14.setText("05");
        jPanel2.add(cell14);

        cell15.setText("06");
        jPanel2.add(cell15);

        cell16.setText("07");
        cell16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cell16ActionPerformed(evt);
            }
        });
        jPanel2.add(cell16);

        cell17.setText("08");
        jPanel2.add(cell17);

        cell18.setText("09");
        jPanel2.add(cell18);

        cell19.setText("10");
        jPanel2.add(cell19);

        cell20.setText("11");
        jPanel2.add(cell20);

        cell21.setText("12");
        jPanel2.add(cell21);

        cell22.setText("13");
        cell22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cell22ActionPerformed(evt);
            }
        });
        jPanel2.add(cell22);

        cell23.setText("14");
        jPanel2.add(cell23);

        cell24.setText("15");
        cell24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cell24ActionPerformed(evt);
            }
        });
        jPanel2.add(cell24);

        cell25.setText("16");
        jPanel2.add(cell25);

        cell27.setText("17");
        jPanel2.add(cell27);

        cell28.setText("18");
        jPanel2.add(cell28);

        cell29.setText("19");
        jPanel2.add(cell29);

        cell30.setText("20");
        cell30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cell30ActionPerformed(evt);
            }
        });
        jPanel2.add(cell30);

        cell31.setText("21");
        jPanel2.add(cell31);

        cell32.setText("22");
        jPanel2.add(cell32);

        cell33.setText("23");
        jPanel2.add(cell33);

        cell34.setText("24");
        jPanel2.add(cell34);

        cell35.setText("25");
        jPanel2.add(cell35);

        cell36.setText("26");
        jPanel2.add(cell36);

        cell37.setText("27");
        jPanel2.add(cell37);

        cell38.setText("28");
        jPanel2.add(cell38);

        cell39.setText("29");
        jPanel2.add(cell39);

        cell40.setText("30");
        jPanel2.add(cell40);
        jPanel2.add(cell41);
        jPanel2.add(cell42);
        jPanel2.add(cell43);
        jPanel2.add(cell44);
        jPanel2.add(cell45);
        jPanel2.add(cell46);
        jPanel2.add(cell47);
        jPanel2.add(cell48);
        jPanel2.add(cell49);
        jPanel2.add(cell50);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 105, 580, 240));

        jPanel4.setBackground(new java.awt.Color(102, 204, 255));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jLabel1.setBackground(new java.awt.Color(51, 153, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Calendário");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 228, 14, 229);
        jPanel4.add(jLabel1, gridBagConstraints);

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 526, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 299, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cell1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cell1ActionPerformed

    private void cell2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cell2ActionPerformed

    private void cell3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cell3ActionPerformed

    private void cell7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cell7ActionPerformed

    private void cell16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cell16ActionPerformed

    private void cell22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cell22ActionPerformed

    private void cell24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cell24ActionPerformed

    private void cell30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cell30ActionPerformed

    private void cell8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cell8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(meusus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(meusus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(meusus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(meusus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new meusus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private meusus.Cell cell1;
    private meusus.Cell cell10;
    private meusus.Cell cell11;
    private meusus.Cell cell12;
    private meusus.Cell cell13;
    private meusus.Cell cell14;
    private meusus.Cell cell15;
    private meusus.Cell cell16;
    private meusus.Cell cell17;
    private meusus.Cell cell18;
    private meusus.Cell cell19;
    private meusus.Cell cell2;
    private meusus.Cell cell20;
    private meusus.Cell cell21;
    private meusus.Cell cell22;
    private meusus.Cell cell23;
    private meusus.Cell cell24;
    private meusus.Cell cell25;
    private meusus.Cell cell26;
    private meusus.Cell cell27;
    private meusus.Cell cell28;
    private meusus.Cell cell29;
    private meusus.Cell cell3;
    private meusus.Cell cell30;
    private meusus.Cell cell31;
    private meusus.Cell cell32;
    private meusus.Cell cell33;
    private meusus.Cell cell34;
    private meusus.Cell cell35;
    private meusus.Cell cell36;
    private meusus.Cell cell37;
    private meusus.Cell cell38;
    private meusus.Cell cell39;
    private meusus.Cell cell4;
    private meusus.Cell cell40;
    private meusus.Cell cell41;
    private meusus.Cell cell42;
    private meusus.Cell cell43;
    private meusus.Cell cell44;
    private meusus.Cell cell45;
    private meusus.Cell cell46;
    private meusus.Cell cell47;
    private meusus.Cell cell48;
    private meusus.Cell cell49;
    private meusus.Cell cell5;
    private meusus.Cell cell50;
    private meusus.Cell cell6;
    private meusus.Cell cell7;
    private meusus.Cell cell8;
    private meusus.Cell cell9;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
